name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: ./app.spec

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/windows/

  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set env project version
      run: echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV

    - name: Download executable
      uses: actions/download-artifact@v2
      with:
        name: executable

    - name: Create GitHub release
      uses: actions/create-release@v1
      id: create-new-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: Release ${{ env.PACKAGE_VERSION }}

    - name: Upload release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: trydrpc.exe
        asset_name: trydrpc.exe
        asset_content_type: application/vnd.microsoft.portable-executable
